main:
testpackage:
	6g -o complex.6 complex.go
	6g -o msg.6 msg.go
	gopack grc numbers.a complex.6 msg.6

clean:
	rm -rf complex.6 msg.6 numbers.a

testpackage-clean:
	rm -rf complex_test.6

importpath:

